# Generated by Django 5.2.5 on 2025-08-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='article',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
